#!/bin/sh

ROCKS_TREE="/private/tmp/smart-splits-rocks"

exec env \
  XDG_STATE_HOME=/private/tmp \
  XDG_DATA_HOME=/private/tmp \
  nvim --headless -u NONE -i NONE -n \
  --cmd "lua package.path='${ROCKS_TREE}/share/lua/5.1/?.lua;${ROCKS_TREE}/share/lua/5.1/?/init.lua;' .. package.path; package.cpath='${ROCKS_TREE}/lib/lua/5.1/?.so;' .. package.cpath" \
  -l "$@"
