local h = require('tests.helpers')

local function fresh_smart_splits(opts)
  for key, _ in pairs(package.loaded) do
    if key:match('^smart%-splits') then
      package.loaded[key] = nil
    end
  end
  local ss = require('smart-splits')
  ss.setup(vim.tbl_extend('force', { multiplexer_integration = false }, opts or {}))
  return ss
end

describe('move_cursor', function()
  local ss

  before_each(function()
    ss = fresh_smart_splits()
  end)

  after_each(function()
    h.reset_editor()
  end)

  describe('horizontal movement', function()
    it('moves right to next split', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[1])
      ss.move_cursor_right()
      assert.equals(wins[2], h.curwin())
    end)

    it('moves left to previous split', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[2])
      ss.move_cursor_left()
      assert.equals(wins[1], h.curwin())
    end)

    it('moves through 3 splits', function()
      local wins = h.create_vsplits(3)
      h.focus(wins[1])
      ss.move_cursor_right()
      assert.equals(wins[2], h.curwin())
      ss.move_cursor_right()
      assert.equals(wins[3], h.curwin())
    end)
  end)

  describe('vertical movement', function()
    it('moves down to next split', function()
      local wins = h.create_hsplits(2)
      h.focus(wins[1])
      ss.move_cursor_down()
      assert.equals(wins[2], h.curwin())
    end)

    it('moves up to previous split', function()
      local wins = h.create_hsplits(2)
      h.focus(wins[2])
      ss.move_cursor_up()
      assert.equals(wins[1], h.curwin())
    end)
  end)

  describe('at_edge = wrap (default)', function()
    it('wraps right to leftmost split', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[2])
      ss.move_cursor_right()
      assert.equals(wins[1], h.curwin())
    end)

    it('wraps left to rightmost split', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[1])
      ss.move_cursor_left()
      assert.equals(wins[2], h.curwin())
    end)

    it('wraps down to topmost split', function()
      local wins = h.create_hsplits(2)
      h.focus(wins[2])
      ss.move_cursor_down()
      assert.equals(wins[1], h.curwin())
    end)

    it('wraps up to bottommost split', function()
      local wins = h.create_hsplits(2)
      h.focus(wins[1])
      ss.move_cursor_up()
      assert.equals(wins[2], h.curwin())
    end)
  end)

  describe('at_edge = stop', function()
    before_each(function()
      ss = fresh_smart_splits({ at_edge = 'stop' })
    end)

    it('stays at rightmost split', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[2])
      ss.move_cursor_right()
      assert.equals(wins[2], h.curwin())
    end)

    it('stays at leftmost split', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[1])
      ss.move_cursor_left()
      assert.equals(wins[1], h.curwin())
    end)
  end)

  describe('at_edge = split', function()
    before_each(function()
      ss = fresh_smart_splits({ at_edge = 'split' })
    end)

    it('creates a new split when moving right at edge', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[2])
      local win_count = #vim.api.nvim_tabpage_list_wins(0)
      ss.move_cursor_right()
      local new_win_count = #vim.api.nvim_tabpage_list_wins(0)
      assert.equals(win_count + 1, new_win_count)
    end)

    it('creates a new split when moving down at edge', function()
      local wins = h.create_hsplits(2)
      h.focus(wins[2])
      local win_count = #vim.api.nvim_tabpage_list_wins(0)
      ss.move_cursor_down()
      local new_win_count = #vim.api.nvim_tabpage_list_wins(0)
      assert.equals(win_count + 1, new_win_count)
    end)
  end)

  describe('single window', function()
    it('wraps to self with at_edge=wrap', function()
      h.reset_editor()
      local win = h.curwin()
      ss.move_cursor_right()
      assert.equals(win, h.curwin())
    end)

    it('stays with at_edge=stop', function()
      ss = fresh_smart_splits({ at_edge = 'stop' })
      h.reset_editor()
      local win = h.curwin()
      ss.move_cursor_right()
      assert.equals(win, h.curwin())
    end)
  end)
end)
