local h = require('tests.helpers')

local function fresh_smart_splits()
  for key, _ in pairs(package.loaded) do
    if key:match('^smart%-splits') then
      package.loaded[key] = nil
    end
  end
  local ss = require('smart-splits')
  ss.setup({ multiplexer_integration = false })
  return ss
end

describe('resize', function()
  local ss

  before_each(function()
    ss = fresh_smart_splits()
  end)

  after_each(function()
    h.reset_editor()
  end)

  describe('horizontal (2 vertical splits)', function()
    it('resize_right increases left pane width', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[1])
      local width_before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_right(3)
      local width_after = vim.api.nvim_win_get_width(wins[1])
      assert.equals(3, width_after - width_before)
    end)

    it('resize_left decreases left pane width', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[1])
      local width_before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_left(3)
      local width_after = vim.api.nvim_win_get_width(wins[1])
      assert.equals(-3, width_after - width_before)
    end)

    it('resize_right from right pane decreases right pane width', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[2])
      local width_before = vim.api.nvim_win_get_width(wins[2])
      ss.resize_right(3)
      local width_after = vim.api.nvim_win_get_width(wins[2])
      assert.equals(-3, width_after - width_before)
    end)

    it('resize_left from right pane increases right pane width', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[2])
      local width_before = vim.api.nvim_win_get_width(wins[2])
      ss.resize_left(3)
      local width_after = vim.api.nvim_win_get_width(wins[2])
      assert.equals(3, width_after - width_before)
    end)

    it('does not move cursor during resize', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[1])
      ss.resize_right(3)
      assert.equals(wins[1], h.curwin())
    end)
  end)

  describe('vertical (2 horizontal splits)', function()
    it('resize_down increases top pane height', function()
      local wins = h.create_hsplits(2)
      h.focus(wins[1])
      local height_before = vim.api.nvim_win_get_height(wins[1])
      ss.resize_down(3)
      local height_after = vim.api.nvim_win_get_height(wins[1])
      assert.equals(3, height_after - height_before)
    end)

    it('resize_up decreases top pane height', function()
      local wins = h.create_hsplits(2)
      h.focus(wins[1])
      local height_before = vim.api.nvim_win_get_height(wins[1])
      ss.resize_up(3)
      local height_after = vim.api.nvim_win_get_height(wins[1])
      assert.equals(-3, height_after - height_before)
    end)

    it('does not move cursor during resize', function()
      local wins = h.create_hsplits(2)
      h.focus(wins[1])
      ss.resize_down(3)
      assert.equals(wins[1], h.curwin())
    end)
  end)

  describe('3 splits', function()
    it('resize_right from middle pane grows it rightward', function()
      local wins = h.create_vsplits(3)
      h.focus(wins[2])
      local width_before = vim.api.nvim_win_get_width(wins[2])
      ss.resize_right(3)
      local width_after = vim.api.nvim_win_get_width(wins[2])
      assert.equals(3, width_after - width_before)
    end)

    it('resize_left from middle pane shrinks it', function()
      local wins = h.create_vsplits(3)
      h.focus(wins[2])
      local width_before = vim.api.nvim_win_get_width(wins[2])
      ss.resize_left(3)
      local width_after = vim.api.nvim_win_get_width(wins[2])
      assert.equals(-3, width_after - width_before)
    end)
  end)

  describe('ignored buftypes', function()
    it('still resizes when current window is ignored (2 windows, only boundary)', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[1])
      h.set_buftype(wins[1], 'nofile')
      local width_before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_right(3)
      local width_after = vim.api.nvim_win_get_width(wins[1])
      assert.equals(3, width_after - width_before)
    end)

    it('still resizes when neighbor is ignored (2 windows, only boundary)', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[1])
      h.set_buftype(wins[2], 'nofile')
      local width_before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_right(3)
      local width_after = vim.api.nvim_win_get_width(wins[1])
      assert.equals(3, width_after - width_before)
    end)

    it('skips ignored window for layout resolution (3 windows)', function()
      local wins = h.create_vsplits(3)
      -- wins[1] is ignored, cursor in wins[2] (middle)
      h.set_buftype(wins[1], 'nofile')
      h.focus(wins[2])
      local ignored_width_before = vim.api.nvim_win_get_width(wins[1])
      local middle_width_before = vim.api.nvim_win_get_width(wins[2])
      ss.resize_left(3)
      local ignored_width_after = vim.api.nvim_win_get_width(wins[1])
      local middle_width_after = vim.api.nvim_win_get_width(wins[2])
      -- ignored window should not change
      assert.equals(0, ignored_width_after - ignored_width_before)
      -- middle window shrinks leftward (boundary with right window moves)
      assert.equals(-3, middle_width_after - middle_width_before)
    end)
  end)

  describe('default amount', function()
    it('uses config default_amount when no amount given', function()
      local wins = h.create_vsplits(2)
      h.focus(wins[1])
      local width_before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_right()
      local width_after = vim.api.nvim_win_get_width(wins[1])
      -- default_amount is 3
      assert.equals(3, width_after - width_before)
    end)
  end)
end)
