local h = require('tests.helpers')

local function fresh_smart_splits(opts)
  for key, _ in pairs(package.loaded) do
    if key:match('^smart%-splits') then
      package.loaded[key] = nil
    end
  end
  local ss = require('smart-splits')
  ss.setup(vim.tbl_extend('force', { multiplexer_integration = false }, opts or {}))
  return ss
end

describe('swap_buf', function()
  local ss

  before_each(function()
    ss = fresh_smart_splits()
  end)

  after_each(function()
    h.reset_editor()
  end)

  describe('horizontal swaps', function()
    it('swaps buffers between left and right splits', function()
      local wins = h.create_vsplits(2)
      h.unique_buffers(wins)
      local buf1 = vim.api.nvim_win_get_buf(wins[1])
      local buf2 = vim.api.nvim_win_get_buf(wins[2])
      h.focus(wins[1])
      ss.swap_buf_right()
      assert.equals(buf2, vim.api.nvim_win_get_buf(wins[1]))
      assert.equals(buf1, vim.api.nvim_win_get_buf(wins[2]))
    end)

    it('cursor stays in original window by default', function()
      local wins = h.create_vsplits(2)
      h.unique_buffers(wins)
      h.focus(wins[1])
      ss.swap_buf_right()
      assert.equals(wins[1], h.curwin())
    end)

    it('cursor follows buffer when cursor_follows_swapped_bufs=true', function()
      ss = fresh_smart_splits({ cursor_follows_swapped_bufs = true })
      local wins = h.create_vsplits(2)
      h.unique_buffers(wins)
      h.focus(wins[1])
      ss.swap_buf_right()
      assert.equals(wins[2], h.curwin())
    end)

    it('cursor follows buffer with move_cursor opt override', function()
      local wins = h.create_vsplits(2)
      h.unique_buffers(wins)
      h.focus(wins[1])
      ss.swap_buf_right({ move_cursor = true })
      assert.equals(wins[2], h.curwin())
    end)
  end)

  describe('vertical swaps', function()
    it('swaps buffers between top and bottom splits', function()
      local wins = h.create_hsplits(2)
      h.unique_buffers(wins)
      local buf1 = vim.api.nvim_win_get_buf(wins[1])
      local buf2 = vim.api.nvim_win_get_buf(wins[2])
      h.focus(wins[1])
      ss.swap_buf_down()
      assert.equals(buf2, vim.api.nvim_win_get_buf(wins[1]))
      assert.equals(buf1, vim.api.nvim_win_get_buf(wins[2]))
    end)
  end)

  describe('wrapping', function()
    it('wraps swap from rightmost to leftmost', function()
      local wins = h.create_vsplits(2)
      h.unique_buffers(wins)
      local buf1 = vim.api.nvim_win_get_buf(wins[1])
      local buf2 = vim.api.nvim_win_get_buf(wins[2])
      h.focus(wins[2])
      ss.swap_buf_right()
      assert.equals(buf2, vim.api.nvim_win_get_buf(wins[1]))
      assert.equals(buf1, vim.api.nvim_win_get_buf(wins[2]))
    end)

    it('wraps swap from leftmost to rightmost', function()
      local wins = h.create_vsplits(2)
      h.unique_buffers(wins)
      local buf1 = vim.api.nvim_win_get_buf(wins[1])
      local buf2 = vim.api.nvim_win_get_buf(wins[2])
      h.focus(wins[1])
      ss.swap_buf_left()
      assert.equals(buf2, vim.api.nvim_win_get_buf(wins[1]))
      assert.equals(buf1, vim.api.nvim_win_get_buf(wins[2]))
    end)
  end)

  describe('3 splits', function()
    it('swaps middle with right', function()
      local wins = h.create_vsplits(3)
      h.unique_buffers(wins)
      local buf2 = vim.api.nvim_win_get_buf(wins[2])
      local buf3 = vim.api.nvim_win_get_buf(wins[3])
      h.focus(wins[2])
      ss.swap_buf_right()
      assert.equals(buf3, vim.api.nvim_win_get_buf(wins[2]))
      assert.equals(buf2, vim.api.nvim_win_get_buf(wins[3]))
    end)
  end)
end)
