---@module 'busted'

local helpers = require('tests.helpers')

describe('resize', function()
  local ss

  before_each(function()
    helpers.reset_plugin()
    ss = require('smart-splits')
  end)

  after_each(function()
    helpers.reset_editor()
    helpers.reset_plugin()
  end)

  describe('horizontal', function()
    it('grows the left pane moving right', function()
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[1])
      local before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_right(3)
      assert.equals(3, vim.api.nvim_win_get_width(wins[1]) - before)
    end)

    it('shrinks the left pane moving left', function()
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[1])
      local before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_left(3)
      assert.equals(-3, vim.api.nvim_win_get_width(wins[1]) - before)
    end)

    it('shrinks the right pane moving right', function()
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[2])
      local before = vim.api.nvim_win_get_width(wins[2])
      ss.resize_right(3)
      assert.equals(-3, vim.api.nvim_win_get_width(wins[2]) - before)
    end)

    it('grows the right pane moving left', function()
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[2])
      local before = vim.api.nvim_win_get_width(wins[2])
      ss.resize_left(3)
      assert.equals(3, vim.api.nvim_win_get_width(wins[2]) - before)
    end)

    it('leaves the cursor where it was', function()
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[1])
      ss.resize_right(3)
      assert.equals(wins[1], helpers.curwin())
    end)
  end)

  describe('vertical', function()
    it('grows the top pane moving down', function()
      local wins = helpers.create_hsplits(2)
      helpers.focus(wins[1])
      local before = vim.api.nvim_win_get_height(wins[1])
      ss.resize_down(3)
      assert.equals(3, vim.api.nvim_win_get_height(wins[1]) - before)
    end)

    it('shrinks the top pane moving up', function()
      local wins = helpers.create_hsplits(2)
      helpers.focus(wins[1])
      local before = vim.api.nvim_win_get_height(wins[1])
      ss.resize_up(3)
      assert.equals(-3, vim.api.nvim_win_get_height(wins[1]) - before)
    end)

    it('leaves the cursor where it was', function()
      local wins = helpers.create_hsplits(2)
      helpers.focus(wins[1])
      ss.resize_down(3)
      assert.equals(wins[1], helpers.curwin())
    end)
  end)

  describe('3 splits', function()
    it('grows the middle pane rightward', function()
      local wins = helpers.create_vsplits(3)
      helpers.focus(wins[2])
      local before = vim.api.nvim_win_get_width(wins[2])
      ss.resize_right(3)
      assert.equals(3, vim.api.nvim_win_get_width(wins[2]) - before)
    end)

    it('shrinks the middle pane leftward', function()
      local wins = helpers.create_vsplits(3)
      helpers.focus(wins[2])
      local before = vim.api.nvim_win_get_width(wins[2])
      ss.resize_left(3)
      assert.equals(-3, vim.api.nvim_win_get_width(wins[2]) - before)
    end)
  end)

  describe('ignored buftypes', function()
    it('resizes when the current window is ignored', function()
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[1])
      helpers.set_buftype(wins[1], 'nofile')
      local before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_right(3)
      assert.equals(3, vim.api.nvim_win_get_width(wins[1]) - before)
    end)

    it('resizes when the neighbor is ignored', function()
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[1])
      helpers.set_buftype(wins[2], 'nofile')
      local before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_right(3)
      assert.equals(3, vim.api.nvim_win_get_width(wins[1]) - before)
    end)

    it('leaves an ignored window alone when resolving the layout', function()
      local wins = helpers.create_vsplits(3)
      helpers.set_buftype(wins[1], 'nofile')
      helpers.focus(wins[2])
      local ignored_before = vim.api.nvim_win_get_width(wins[1])
      local middle_before = vim.api.nvim_win_get_width(wins[2])
      ss.resize_left(3)
      assert.equals(0, vim.api.nvim_win_get_width(wins[1]) - ignored_before)
      assert.equals(-3, vim.api.nvim_win_get_width(wins[2]) - middle_before)
    end)

    it('respects a resize specific ignore list', function()
      ss.setup({ resize = { ignored_filetypes = { 'only-resize' } } })
      local wins = helpers.create_vsplits(3)
      helpers.set_filetype(wins[1], 'only-resize')
      helpers.focus(wins[2])
      local ignored_before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_left(3)
      assert.equals(0, vim.api.nvim_win_get_width(wins[1]) - ignored_before)
    end)
  end)

  describe('amount', function()
    it('falls back to resize.amount', function()
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[1])
      local before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_right()
      assert.equals(3, vim.api.nvim_win_get_width(wins[1]) - before)
    end)

    it('uses a configured resize.amount', function()
      ss.setup({ resize = { amount = 5 } })
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[1])
      local before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_right()
      assert.equals(5, vim.api.nvim_win_get_width(wins[1]) - before)
    end)

    it('accepts a bare number', function()
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[1])
      local before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_right(7)
      assert.equals(7, vim.api.nvim_win_get_width(wins[1]) - before)
    end)

    it('accepts an options table', function()
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[1])
      local before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_right({ amount = 7 })
      assert.equals(7, vim.api.nvim_win_get_width(wins[1]) - before)
    end)

    it('prefers a per call amount over the configured one', function()
      ss.setup({ resize = { amount = 5 } })
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[1])
      local before = vim.api.nvim_win_get_width(wins[1])
      ss.resize_right({ amount = 2 })
      assert.equals(2, vim.api.nvim_win_get_width(wins[1]) - before)
    end)
  end)

  describe('window filling the axis', function()
    -- nvim shrinks a window that already fills the axis into `cmdheight` and
    -- there is no way to get the space back, so core must not try.
    -- https://github.com/mrjones2014/smart-splits.nvim/issues/336
    it('does not change the height of a single window', function()
      helpers.reset_editor()
      local before = vim.api.nvim_win_get_height(0)
      ss.resize_up(3)
      assert.equals(before, vim.api.nvim_win_get_height(0))
      ss.resize_down(3)
      assert.equals(before, vim.api.nvim_win_get_height(0))
    end)

    it('does not change the width of a single window', function()
      helpers.reset_editor()
      local before = vim.api.nvim_win_get_width(0)
      ss.resize_left(3)
      assert.equals(before, vim.api.nvim_win_get_width(0))
      ss.resize_right(3)
      assert.equals(before, vim.api.nvim_win_get_width(0))
    end)

    it('does not change the height of a full height window beside another', function()
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[1])
      local before = vim.api.nvim_win_get_height(wins[1])
      ss.resize_up(3)
      assert.equals(before, vim.api.nvim_win_get_height(wins[1]))
    end)

    it('does not grow cmdheight', function()
      helpers.reset_editor()
      local before = vim.o.cmdheight
      ss.resize_up(3)
      assert.equals(before, vim.o.cmdheight)
    end)
  end)

  describe('backend delegation', function()
    it('delegates a horizontal resize when the window spans the full width', function()
      local backend, calls = helpers.mock_backend()
      ss.setup({ mux = { backend = backend } })
      helpers.create_hsplits(2)
      ss.resize_right(4)
      assert.same({ 'resize', 'right', { amount = 4 } }, helpers.find_call(calls, 'resize'))
    end)

    it('forwards a per call amount from an options table', function()
      local backend, calls = helpers.mock_backend()
      ss.setup({ mux = { backend = backend } })
      helpers.create_hsplits(2)
      ss.resize_right({ amount = 9 })
      assert.same({ 'resize', 'right', { amount = 9 } }, helpers.find_call(calls, 'resize'))
    end)

    it('forwards the configured amount when the call gives none', function()
      local backend, calls = helpers.mock_backend()
      ss.setup({ mux = { backend = backend }, resize = { amount = 6 } })
      helpers.create_hsplits(2)
      ss.resize_right()
      assert.same({ 'resize', 'right', { amount = 6 } }, helpers.find_call(calls, 'resize'))
    end)

    it('delegates a vertical resize when the window spans the full height', function()
      local backend, calls = helpers.mock_backend()
      ss.setup({ mux = { backend = backend } })
      helpers.create_vsplits(2)
      ss.resize_up(4)
      assert.same({ 'resize', 'up', { amount = 4 } }, helpers.find_call(calls, 'resize'))
    end)

    it('does not delegate when nvim can do the resize', function()
      local backend, calls = helpers.mock_backend()
      ss.setup({ mux = { backend = backend } })
      local wins = helpers.create_vsplits(2)
      helpers.focus(wins[1])
      ss.resize_right(3)
      assert.is_false(vim.tbl_contains(helpers.ops(calls), 'resize'))
    end)

    it('does not resize in nvim when the backend declines', function()
      ss.setup({ mux = { backend = helpers.mock_backend() } })
      helpers.reset_editor()
      local before = vim.api.nvim_win_get_height(0)
      ss.resize_up(3)
      assert.equals(before, vim.api.nvim_win_get_height(0))
    end)

    it('skips a backend that cannot resize', function()
      local backend, calls = helpers.mock_backend({ resize = false })
      ss.setup({ mux = { backend = backend } })
      helpers.reset_editor()
      local before = vim.api.nvim_win_get_height(0)
      ss.resize_up(3)
      assert.is_false(vim.tbl_contains(helpers.ops(calls), 'resize'))
      assert.equals(before, vim.api.nvim_win_get_height(0))
    end)

    it('survives a backend that throws', function()
      local backend = helpers.mock_backend({
        resize = function()
          error('resize exploded')
        end,
      })
      ss.setup({ mux = { backend = backend } })
      helpers.reset_editor()
      local before = vim.api.nvim_win_get_height(0)
      ss.resize_up(3)
      assert.equals(before, vim.api.nvim_win_get_height(0))
    end)
  end)
end)
