name: Check PR Title
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  check-pr-title:
    name: Check PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          scopes: |
            docs
            api
            mux
